"""initial_schema

Revision ID: 4efd7f29e80e
Revises: 
Create Date: 2026-09-01 20:09:57.833345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4efd7f29e80e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_alerts_phc_created', ['phc_id', 'created_at'], unique=False)
        batch_op.create_index('ix_alerts_status_severity', ['status', 'severity'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_audit_action_ts', ['action', 'timestamp'], unique=False)
        batch_op.create_index('ix_audit_user_ts', ['user_id', 'timestamp'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.alter_column('total_beds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('occupied_beds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('available_beds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('icu_beds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('icu_occupied',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('oxygen_beds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('oxygen_occupied',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('isolation_beds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('isolation_occupied',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('occupancy_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('is_brics_member',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_countries_code'), ['code'], unique=True)

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_district_state_name', ['state_id', 'name'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('emergency_events', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('footfall_multiplier',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('medicine_demand_multiplier',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('bed_occupancy_multiplier',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('staff_strain_multiplier',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'districts', ['affected_district_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('federated_nodes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('local_data_points',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('local_accuracy',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('last_sync_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('federated_training_rounds', schema=None) as batch_op:
        batch_op.alter_column('local_loss',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('local_accuracy',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('global_aggregated_accuracy',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('weights_divergence',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('parameters_size_kb',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_fed_round_node', ['round_number', 'node_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'federated_nodes', ['node_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.alter_column('forecast_horizon_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('demand_change_percent',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('confidence_score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('trend',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('generated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_forecast_phc_med_horizon', ['phc_id', 'medicine_id', 'forecast_horizon_days'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('current_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reorder_threshold',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('incoming_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_inventory_phc_id', ['phc_id'], unique=False)
        batch_op.create_unique_constraint('uq_inventory_phc_medicine', ['phc_id', 'medicine_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performed_by', sa.String(length=120), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_inv_txn_inventory_ts', ['inventory_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transactions_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('medicine_consumption', schema=None) as batch_op:
        batch_op.alter_column('is_anomaly',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_consumption_phc_med_date', ['phc_id', 'medicine_id', 'date'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('unit_cost_inr',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('standard_daily_demand',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('safety_stock_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('shelf_life_months',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.alter_column('evaluated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_model_metric_name_type', ['model_name', 'metric_type'], unique=False)

    with op.batch_alter_table('patient_footfall', schema=None) as batch_op:
        batch_op.alter_column('outpatient_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('inpatient_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('emergency_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fever_respiratory_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_footfall',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_surge_anomaly',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_footfall_phc_date', ['phc_id', 'date'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('phcs', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('catchment_population',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('current_risk_score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('risk_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_phc_district_risk', ['district_id', 'risk_category'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('redistribution_recommendations', schema=None) as batch_op:
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('estimated_transit_hours',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_redist_rec_status_urgency', ['status', 'urgency'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'districts', ['dest_district_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'districts', ['source_district_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'phcs', ['source_phc_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'phcs', ['dest_phc_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('redistribution_transactions', schema=None) as batch_op:
        batch_op.alter_column('current_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('dispatched_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('temperature_logged_celsius',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'redistribution_recommendations', ['recommendation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.alter_column('current_stock',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('daily_consumption_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('supplier_lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('calculated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('ix_risk_phc_med_calc', ['phc_id', 'medicine_id', 'calculated_at'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('sanctioned_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('active_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('present_today',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('on_leave',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('attendance_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint('uq_staff_phc_role', ['phc_id', 'role_type'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.alter_column('scheduled',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('present',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('absent',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('on_leave',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('attendance_percentage',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.create_index('ix_staff_att_staff_date', ['staff_id', 'date'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint('uq_state_country_code', ['country_id', 'code'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reliability_score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('state_coverage',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_suppliers_code'), ['code'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'])
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('last_login')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_code'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('state_coverage',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('reliability_score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['id'])
        batch_op.drop_constraint('uq_state_country_code', type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'])
        batch_op.drop_index('ix_staff_att_staff_date')
        batch_op.alter_column('attendance_percentage',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('on_leave',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('absent',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('present',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('scheduled',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'])
        batch_op.drop_constraint('uq_staff_phc_role', type_='unique')
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('attendance_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('on_leave',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('present_today',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('active_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sanctioned_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'])
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'])
        batch_op.drop_index('ix_risk_phc_med_calc')
        batch_op.alter_column('calculated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('supplier_lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('daily_consumption_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('current_stock',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('redistribution_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'redistribution_recommendations', ['recommendation_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('temperature_logged_celsius',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('dispatched_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('current_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('redistribution_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'])
        batch_op.create_foreign_key(None, 'phcs', ['dest_phc_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['source_district_id'], ['id'])
        batch_op.create_foreign_key(None, 'phcs', ['source_phc_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['dest_district_id'], ['id'])
        batch_op.drop_index('ix_redist_rec_status_urgency')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('estimated_transit_hours',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('phcs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])
        batch_op.drop_index('ix_phc_district_risk')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('risk_category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('current_risk_score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('catchment_population',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('patient_footfall', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'])
        batch_op.drop_index('ix_footfall_phc_date')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_surge_anomaly',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('total_footfall',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fever_respiratory_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('emergency_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('inpatient_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('outpatient_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('model_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_model_metric_name_type')
        batch_op.alter_column('evaluated_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('shelf_life_months',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('safety_stock_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('standard_daily_demand',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('unit_cost_inr',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('medicine_consumption', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'])
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'])
        batch_op.drop_index('ix_consumption_phc_med_date')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_anomaly',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_timestamp'))
        batch_op.drop_index('ix_inv_txn_inventory_ts')
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('performed_by')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'])
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'])
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'])
        batch_op.drop_constraint('uq_inventory_phc_medicine', type_='unique')
        batch_op.drop_index('ix_inventory_phc_id')
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('incoming_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reorder_threshold',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('current_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('expiry_date')

    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'])
        batch_op.create_foreign_key(None, 'medicines', ['medicine_id'], ['id'])
        batch_op.drop_index('ix_forecast_phc_med_horizon')
        batch_op.alter_column('generated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('trend',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('confidence_score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('demand_change_percent',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('forecast_horizon_days',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('federated_training_rounds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'federated_nodes', ['node_id'], ['id'])
        batch_op.drop_index('ix_fed_round_node')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('parameters_size_kb',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('weights_divergence',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('global_aggregated_accuracy',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('local_accuracy',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('local_loss',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('federated_nodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('last_sync_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('local_accuracy',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('local_data_points',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('emergency_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'districts', ['affected_district_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('staff_strain_multiplier',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('bed_occupancy_multiplier',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('medicine_demand_multiplier',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('footfall_multiplier',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['id'])
        batch_op.drop_index('ix_district_state_name')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_code'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_brics_member',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'])
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('occupancy_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('isolation_occupied',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('isolation_beds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('oxygen_occupied',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('oxygen_beds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('icu_occupied',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('icu_beds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('available_beds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('occupied_beds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_beds',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_index('ix_audit_user_ts')
        batch_op.drop_index('ix_audit_action_ts')
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'phcs', ['phc_id'], ['id'])
        batch_op.drop_index('ix_alerts_status_severity')
        batch_op.drop_index('ix_alerts_phc_created')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
